package com.agentic.urlshortener.orchestration.agent;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.springframework.stereotype.Component;

import com.agentic.urlshortener.orchestration.config.OrchestrationProperties;
import com.agentic.urlshortener.orchestration.domain.FailureClass;
import com.agentic.urlshortener.orchestration.domain.StageType;
import com.agentic.urlshortener.orchestration.knowledge.CapabilityCatalog;
import com.agentic.urlshortener.orchestration.knowledge.CapabilityEntry;

import tools.jackson.databind.JsonNode;

/**
 * DOCUMENTATION: generates the API changelog, the capability description with its acceptance
 * criteria, and the release/rollback runbook, and checks that the repository documentation named by
 * the catalog mentions the capability. The result of that check is recorded in a marker line that
 * validation and policy DOC-001 read.
 */
@Component
public class DocumentationAgent implements StageAgent {

    private static final Pattern MARKER = Pattern.compile(
            "<!-- documentation-check: repositoryDocsUpdated=(true|false); degraded=(true|false) -->");

    private final CapabilityCatalog catalog;
    private final Path codebaseRoot;

    public DocumentationAgent(CapabilityCatalog catalog, OrchestrationProperties properties) {
        this.catalog = catalog;
        this.codebaseRoot = Path.of(properties.codebaseRoot()).toAbsolutePath().normalize();
    }

    @Override
    public StageType stageType() {
        return StageType.DOCUMENTATION;
    }

    @Override
    public String agentId() {
        return "documenter@1.0";
    }

    @Override
    public Set<AgentPermission> permissions() {
        return Set.of();
    }

    @Override
    public StageResult execute(StageContext context) {
        JsonNode design = context.inputJson("DESIGN");
        String capabilityId = design.path("releasePlan").path("capability").asString();
        CapabilityEntry capability = catalog.get(capabilityId).orElse(null);
        if (capability == null) {
            return new StageResult.Failed(FailureClass.PERMANENT, "the design names an unknown capability: " + capabilityId);
        }
        Map<String, String> criteria = AgentInputs.criteria(context.inputJson("NORMALIZED_REQUIREMENT"));

        StringBuilder doc = new StringBuilder();
        doc.append("# ").append(capability.name()).append(" (`").append(capabilityId).append("`)\n\n");
        doc.append("Generated by ").append(agentId()).append(" for run ").append(context.runId()).append(".\n\n");
        doc.append("## API changelog\n\n");
        if (design.path("apiChanges").isEmpty()) {
            doc.append("No public API change.\n");
        }
        for (JsonNode change : design.path("apiChanges")) {
            doc.append("- **").append(change.path("contractVersion").asString()).append("** `").append(change.path("operation").asString())
                    .append("`: ").append(change.path("change").asString()).append(" (").append(change.path("compatibility").asString())
                    .append(")\n");
        }
        for (JsonNode change : design.path("schemaChanges")) {
            doc.append("- Schema `").append(change.path("migration").asString()).append("`: ").append(change.path("change").asString())
                    .append(" (").append(change.path("compatibility").asString()).append(")\n");
        }
        doc.append("\n## Behavior\n\n");
        criteria.forEach((id, text) -> doc.append("- ").append(id).append(": ").append(text).append('\n'));
        doc.append("\n## Runbook\n\n");
        doc.append("- **Release**: ").append(design.path("releasePlan").path("strategy").asString())
                .append("; parameters ").append(design.path("releasePlan").path("parameters")).append(".\n");
        doc.append("- **Rollback**: ").append(design.path("rollbackPlan").asString()).append('\n');

        List<String> evidence = new ArrayList<>();
        boolean updated = !capability.docAnchors().isEmpty();
        for (CapabilityEntry.DocAnchor anchor : capability.docAnchors()) {
            boolean mentions = mentions(anchor);
            updated &= mentions;
            evidence.add(anchor.path() + (mentions ? " mentions '" : " does not mention '") + anchor.mentions() + "'");
        }
        doc.append("\n## Repository documentation check\n\n");
        evidence.forEach(e -> doc.append("- ").append(e).append('\n'));
        doc.append('\n').append(marker(updated, false)).append('\n');
        return new StageResult.Succeeded(List.of(ArtifactDraft.markdown("DOCUMENTATION", doc.toString())),
                "documentation generated; repository docs updated: " + updated);
    }

    private boolean mentions(CapabilityEntry.DocAnchor anchor) {
        Path file = codebaseRoot.resolve(anchor.path()).normalize();
        if (!file.startsWith(codebaseRoot) || !Files.isRegularFile(file)) {
            return false;
        }
        try {
            return Files.readString(file, StandardCharsets.UTF_8).toLowerCase(Locale.ROOT).contains(anchor.mentions().toLowerCase(Locale.ROOT));
        } catch (IOException e) {
            return false;
        }
    }

    static String marker(boolean repositoryDocsUpdated, boolean degraded) {
        return "<!-- documentation-check: repositoryDocsUpdated=" + repositoryDocsUpdated + "; degraded=" + degraded + " -->";
    }

    /** Whether the documentation artifact records that the repository docs mention the capability. */
    public static boolean repositoryDocsUpdated(String documentation) {
        Matcher matcher = MARKER.matcher(documentation);
        return matcher.find() && Boolean.parseBoolean(matcher.group(1));
    }

    /** Whether the documentation artifact was produced by a fallback (template) path. */
    public static boolean isDegraded(String documentation) {
        Matcher matcher = MARKER.matcher(documentation);
        return matcher.find() && Boolean.parseBoolean(matcher.group(2));
    }
}
