package com.agentic.urlshortener.orchestration.agent;

import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.springframework.stereotype.Component;

import com.agentic.urlshortener.orchestration.config.OrchestrationProperties;
import com.agentic.urlshortener.orchestration.domain.StageType;
import com.agentic.urlshortener.orchestration.knowledge.CapabilityCatalog;
import com.agentic.urlshortener.orchestration.knowledge.CapabilityEntry;

/**
 * Fallback of DOCUMENTATION (FR-REL-03): a fixed template filled with the requirement's acceptance
 * criteria and the design's capability, without the changelog and runbook of the primary agent. The
 * repository documentation check still runs on real files, and the marker records {@code degraded=true},
 * which validation lists and readiness turns into an accepted limitation.
 */
@Component
public class TemplateDocumentationAgent implements StageAgent {

    private final CapabilityCatalog catalog;
    private final Path codebaseRoot;

    public TemplateDocumentationAgent(CapabilityCatalog catalog, OrchestrationProperties properties) {
        this.catalog = catalog;
        this.codebaseRoot = Path.of(properties.codebaseRoot()).toAbsolutePath().normalize();
    }

    @Override
    public StageType stageType() {
        return StageType.DOCUMENTATION;
    }

    @Override
    public String agentId() {
        return "template-documenter@1.0";
    }

    @Override
    public boolean fallback() {
        return true;
    }

    @Override
    public Set<AgentPermission> permissions() {
        return Set.of();
    }

    @Override
    public StageResult execute(StageContext context) {
        String capabilityId = context.input("DESIGN").map(d -> d.json().path("releasePlan").path("capability").asString(""))
                .orElse("");
        CapabilityEntry capability = catalog.get(capabilityId).orElse(null);

        StringBuilder doc = new StringBuilder();
        doc.append("# ").append(capability == null ? "Change documentation" : capability.name())
                .append(" (template, degraded)\n\n");
        doc.append("Generated by the fallback ").append(agentId()).append(" for run ").append(context.runId())
                .append(" because the primary documentation agent failed. The API changelog and runbook are not included; ")
                .append("a reviewer must complete them before release.\n\n");
        doc.append("## Behavior\n\n");
        Map<String, String> criteria = context.input("NORMALIZED_REQUIREMENT")
                .map(n -> AgentInputs.criteria(n.json())).orElse(Map.of());
        if (criteria.isEmpty()) {
            doc.append("- See the requirement document.\n");
        }
        criteria.forEach((id, text) -> doc.append("- ").append(id).append(": ").append(text).append('\n'));

        boolean updated = false;
        doc.append("\n## Repository documentation check\n\n");
        if (capability == null) {
            doc.append("- no catalog capability named by the design; nothing to check\n");
        } else {
            DocumentationAgent.RepositoryCheck check = DocumentationAgent.checkRepositoryDocs(codebaseRoot, capability);
            updated = check.updated();
            check.evidence().forEach(e -> doc.append("- ").append(e).append('\n'));
        }
        doc.append('\n').append(DocumentationAgent.marker(updated, true)).append('\n');
        return new StageResult.Succeeded(List.of(ArtifactDraft.markdown("DOCUMENTATION", doc.toString())),
                "template documentation generated (degraded)");
    }
}
