package com.agentic.urlshortener.support;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import com.agentic.urlshortener.common.util.CanonicalJson;

/**
 * Writes scenario and drill evidence to {@code target/evidence/<scenario>/}. Every file starts with
 * provenance (review RC-4): git commit, generating test, timestamp, JDK, profile, and whether the
 * run contains simulated input. Evidence is copied into {@code docs/} only by
 * {@code scripts/export-evidence.*}, never edited by hand.
 */
public final class EvidenceExporter {

    private static final Path ROOT = Path.of("target", "evidence");

    private final String scenario;
    private final String generatedBy;
    private final boolean simulatedInput;

    public EvidenceExporter(String scenario, Class<?> generatedBy, boolean simulatedInput) {
        this.scenario = scenario;
        this.generatedBy = generatedBy.getName();
        this.simulatedInput = simulatedInput;
    }

    /** Writes {@code {"provenance": …, "evidence": …}} as pretty-stable canonical JSON. */
    public Path json(String name, Object evidence) {
        Map<String, Object> document = new LinkedHashMap<>();
        document.put("provenance", provenance());
        document.put("evidence", evidence instanceof String text ? CanonicalJson.parse(text) : evidence);
        return write(name + ".json", CanonicalJson.write(document));
    }

    /** Writes Markdown with a provenance block at the top. */
    public Path markdown(String name, String markdown) {
        StringBuilder text = new StringBuilder("<!-- provenance: ").append(CanonicalJson.write(provenance())).append(" -->\n\n");
        if (simulatedInput) {
            text.append("> **Simulated input**: human decisions and/or faults in this run were supplied by an automated test ")
                    .append("acting as a labeled demo principal. They are not decisions of the candidate.\n\n");
        }
        text.append(markdown);
        return write(name + ".md", text.toString());
    }

    private Map<String, Object> provenance() {
        Map<String, Object> provenance = new LinkedHashMap<>();
        provenance.put("scenario", scenario);
        provenance.put("generatedBy", generatedBy);
        provenance.put("command", "mvnw test -Dtest=" + generatedBy.substring(generatedBy.lastIndexOf('.') + 1));
        provenance.put("gitCommit", gitCommit());
        provenance.put("generatedAt", Instant.now().truncatedTo(ChronoUnit.SECONDS).toString());
        provenance.put("jdk", System.getProperty("java.version"));
        provenance.put("profile", "test");
        provenance.put("simulatedInput", simulatedInput);
        provenance.put("label", "DEMONSTRATION EVIDENCE - generated by an automated test, not production data");
        return provenance;
    }

    private Path write(String fileName, String content) {
        try {
            Path directory = ROOT.resolve(scenario);
            Files.createDirectories(directory);
            Path file = directory.resolve(fileName);
            Files.writeString(file, content, StandardCharsets.UTF_8);
            return file;
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private static String gitCommit() {
        try {
            Process process = new ProcessBuilder("git", "rev-parse", "HEAD").redirectErrorStream(true).start();
            String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8).trim();
            return process.waitFor(10, TimeUnit.SECONDS) && process.exitValue() == 0 ? output : "unknown";
        } catch (IOException e) {
            return "unknown";
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            return "unknown";
        }
    }
}
