-- V1: application-plane baseline (data-model.md, "Application plane").
-- Additive-only rules for later migrations: see data-model.md "Migration plan".

CREATE TABLE short_link (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(32)   NOT NULL,
    target_url        VARCHAR(2048) NOT NULL,
    created_by        VARCHAR(64)   NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at        TIMESTAMP WITH TIME ZONE,
    click_count       BIGINT        NOT NULL DEFAULT 0,
    last_accessed_at  TIMESTAMP WITH TIME ZONE,
    synthetic         BOOLEAN       NOT NULL DEFAULT FALSE,
    synthetic_run_id  UUID,
    CONSTRAINT uk_short_link_code UNIQUE (code)
);

CREATE INDEX idx_short_link_synthetic_run ON short_link (synthetic_run_id);

-- Click events store no personal identifiers: timestamp and referrer host only (FR-ANL-02).
CREATE TABLE click_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id        BIGINT NOT NULL,
    occurred_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    referrer_host  VARCHAR(255),
    CONSTRAINT fk_click_event_link FOREIGN KEY (link_id) REFERENCES short_link (id) ON DELETE CASCADE
);

CREATE INDEX idx_click_event_link_time ON click_event (link_id, occurred_at);

CREATE TABLE idempotency_record (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumer_id          VARCHAR(64)     NOT NULL,
    idem_key             VARCHAR(128)    NOT NULL,
    request_fingerprint  VARCHAR(64)     NOT NULL,
    response_status      INTEGER         NOT NULL,
    response_body        VARCHAR(100000) NOT NULL,
    link_id              BIGINT,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_idempotency_consumer_key UNIQUE (consumer_id, idem_key),
    CONSTRAINT fk_idempotency_link FOREIGN KEY (link_id) REFERENCES short_link (id) ON DELETE SET NULL
);

-- Capability release flags; rows are created unreleased at startup for every registered capability.
CREATE TABLE capability_release (
    capability_id   VARCHAR(64) PRIMARY KEY,
    released        BOOLEAN     NOT NULL DEFAULT FALSE,
    parameters      VARCHAR(10000),
    changed_by      VARCHAR(64),
    changed_by_run  UUID,
    changed_at      TIMESTAMP WITH TIME ZONE,
    reason          VARCHAR(500),
    version         BIGINT      NOT NULL DEFAULT 0
);
